### ISSUE TITLE
README file was not found

### ISSUE THREAD

**Issue by EliasSalom** [Fullstack-Alfanar/ameer.e-homework#1]
hi ameer, I have been checking your code with the Homework requirement, 
and I think there is a missing readme file that mentions all details of your website, 

**please** do the following steps

1. assignees yourself on this issue
2. fix the issue
3. close the issue

**Comment by ameer1004** [comment]
Hi Elias. 
I put a readme.md. 
please check it and tell me if it's Ok or not. 
thank you
